# Generated by Django 4.2.6 on 2023-12-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_prof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prof',
            old_name='img1',
            new_name='imge1',
        ),
    ]
